# @format
---
name: "Management for 'master' and 'development' branches"

on:
  push:
    branches:
      - master
      - development

jobs:
  checkout:
    runs-on: ubuntu-latest
    name: Perform Checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  tests-run:
    runs-on: ubuntu-latest
    name: Verify tests are all still passing
    needs:
      - checkout
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test

  perform-release:
    runs-on: ubuntu-latest
    needs:
      - checkout
      - tests-run
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npx semantic-release
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Semantic Released
