name: Old Branch Reminder

on:
  schedule:
    - cron: '0 0 * * 1'  # Run on Mondays

jobs:
  check_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checking for Unusued Branches
        uses: arup-group/action-notify-unused-branches@v5
        with:
          daysOld: 45  # Days before a branch is old
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
