# @format
---
name: Implement Code Review

on:
  pull_request:
    - opened
    - reopened
    - ready_for_review
    - synchronize
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:

  check-for-secrets:
    runs-on: "ubuntu-latest"
    name: Check for Secrets in the Code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Yelp's detect-secrets
        uses: RobertFischer/detect-secrets-action@2.0.0
      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build(detect-secrets): Commit the newly-generated .secrets.baseline file"

  tests-run:
    runs-on: ubuntu-latest
    name: Verify tests are all still passing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn install
          yarn test
